// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzqxHO-ZC1RC9nR1DfzrJZ4cHGXucVMug',
    appId: '1:209793279994:web:76160d7eab96be5d776643',
    messagingSenderId: '209793279994',
    projectId: 'controle-estoque-c7892',
    authDomain: 'controle-estoque-c7892.firebaseapp.com',
    storageBucket: 'controle-estoque-c7892.appspot.com',
    measurementId: 'G-123KVL5WSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0U0kki_37a0MFbsQca5ngIOVgZV9jz4',
    appId: '1:209793279994:android:8465ff74dc943779776643',
    messagingSenderId: '209793279994',
    projectId: 'controle-estoque-c7892',
    storageBucket: 'controle-estoque-c7892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtKpzxQ9-9g-u4v1Rsjbu6Esrsr7Y2r-U',
    appId: '1:209793279994:ios:e293dbec56ffe569776643',
    messagingSenderId: '209793279994',
    projectId: 'controle-estoque-c7892',
    storageBucket: 'controle-estoque-c7892.appspot.com',
    iosBundleId: 'com.example.flutterShiftsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtKpzxQ9-9g-u4v1Rsjbu6Esrsr7Y2r-U',
    appId: '1:209793279994:ios:e293dbec56ffe569776643',
    messagingSenderId: '209793279994',
    projectId: 'controle-estoque-c7892',
    storageBucket: 'controle-estoque-c7892.appspot.com',
    iosBundleId: 'com.example.flutterShiftsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzqxHO-ZC1RC9nR1DfzrJZ4cHGXucVMug',
    appId: '1:209793279994:web:a46ddb586dba4403776643',
    messagingSenderId: '209793279994',
    projectId: 'controle-estoque-c7892',
    authDomain: 'controle-estoque-c7892.firebaseapp.com',
    storageBucket: 'controle-estoque-c7892.appspot.com',
    measurementId: 'G-17RKH7SSVZ',
  );

}